 

--1. Retrieve all columns from the customer table.
select *
from customer;
--2. Display only film_id, title, and rating from the film table.
select  film_id, title, rating
from film;
--3. Retrieve the first 15 records from the actor table.
select  *  
from actor
limit  15;
--4. Retrieve all customers and sort them by last_name in ascending order.
select customer_id, first_name, last_name
from customer
order by  last_name asc;
--5. Display payment_id, customer_id, and amount, sorted by amount from lowest to highest.
select payment_id, customer_id, amount
from payment
order by amount asc;
--6. Retrieve customers sorted by:
-- first_name in ascending order
select  *
from  customer
order  by first_name asc;
--  last_name in descending order
select  *
from  customer
order by last_name desc;

--7. Retrieve all payments where the amount is greater than 5.
select *
from payment
where amount >5;

--8. Retrieve all payments where the amount is between 3.99 and 6.99.
select *
from payment
where amount between 3.99 and 6.99;
--9. Retrieve all customers whose first_name starts with the letter J.
select *
from customer
where first_name like 'J%';
--10. Retrieve all films where the description contains the word “Action”.
select *
from film
where description like '%action%';
--11. Retrieve payments greater than 7, sorted by amount in descending order.
SELECT  *
FROM PAYMENT
WHERE AMOUNT >7
ORDER BY AMOUNT  DESC;
--12. Retrieve customers whose first name ends with “n”, sorted alphabetically.
SELECT *
FROM customer
WHERE first_name LIKE '%n'
ORDER BY first_name ASC;
--13. Calculate the total amount spent by each customer.
SELECT customer_id, SUM(amount) AS total_amount_spent
FROM payment
GROUP BY customer_id;
--14. Retrieve the average payment amount per customer.
select customer_id, round(avg(amount),2) as total_amount
from payment
group by customer_id;


--15. Calculate the total revenue generated by each staff member.
SELECT staff_id, SUM(amount) AS total_revenue
FROM payment
GROUP BY staff_id;


--16. Identify the top 5 customers based on total payment amount.
SELECT customer_id, SUM(amount) AS total_payment
FROM payment
GROUP BY customer_id
ORDER BY total_payment DESC
LIMIT 5;

--17. Find the average film length per release year.
SELECT release_year, ROUND(AVG(length), 2) AS avg_film_length
FROM film
GROUP BY release_year
ORDER BY release_year;

--18. Retrieve the highest single payment amount in the payment table.
SELECT payment_id, amount
FROM payment
ORDER BY amount DESC
LIMIT 1;	
--19. Count how many payments each customer has made.
select customer_id,count(amount) total_amount
from payment
group by customer_id
order by total_amount;
--20. Retrieve customers who are active and sort them by first_name.
select customer_id, first_name, last_name, active
from customer
where active=1
order by first_name asc;
